---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: delete-artifact-version.cfg.j2
    dest: "{{ dir_base }}/delete-artifact-version.cfg"
    mode: 0775

- name: template delete-artifact-version
  template:
    src: delete-artifact-version.sh.j2
    dest: "{{ dir_base }}/delete-artifact-version.sh"
    mode: 0775
