---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: automated-versioning-system.cfg.j2
    dest: "{{ dir_base }}/automated-versioning-system.cfg"
    mode: 0775

- name: template automated-versioning-system
  template:
    src: automated-versioning-system.sh.j2
    dest: "{{ dir_base }}/automated-versioning-system.sh"
    mode: 0775
