---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: create-project-from-archetype.cfg.j2
    dest: "{{ dir_base }}/create-project-from-archetype.cfg"
    mode: 0775

- name: template create-project-from-archetype
  template:
    src: create-project-from-archetype.sh.j2
    dest: "{{ dir_base }}/create-project-from-archetype.sh"
    mode: 0775
