---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: manage-dependencies.cfg.j2
    dest: "{{ dir_base }}/manage-dependencies.cfg"
    mode: 0775

- name: template manage-dependencies
  template:
    src: manage-dependencies.sh.j2
    dest: "{{ dir_base }}/manage-dependencies.sh"
    mode: 0775
