---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: create-shop-from-baseshop.cfg.j2
    dest: "{{ dir_base }}/create-shop-from-baseshop.cfg"
    mode: 0775

- name: template create-shop-from-baseshop
  template:
    src: create-shop-from-baseshop.sh.j2
    dest: "{{ dir_base }}/create-shop-from-baseshop.sh"
    mode: 0775
