---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: deploy-application.cfg.j2
    dest: "{{ dir_base }}/deploy-application.cfg"
    mode: 0775

- name: template deploy-application
  template:
    src: deploy-application.sh.j2
    dest: "{{ dir_base }}/deploy-application.sh"
    mode: 0775
