---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: Limpiamos los directorios de destino para asegurar un despliegue limpio
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ remote_directories }}"

- name: Creamos los directorios en remoto antes de ubicar los artefactos
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ remote_directories }}"

- name: Descomprimimos el contenido del zip en remoto
  unarchive:
    src: "{{ artifact_url }}"
    dest: "{{ item }}"
    remote_src: yes
  with_items: "{{ remote_directories }}"
