---

- hosts: localhost
  connection: local
  tasks:
  - name: Prueba de versiones
    debug:
      msg: "hola amigo"
  - name: insert/update configuration using a local file
    copy:
      src: "/tmp/ojo1/"
      dest: "/tmp/ojo2"
